name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up CMake
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    # Step 3: Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    # Step 5: Create a build directory
    - name: Create build directory
      run: mkdir -p build

    # Step 6: Configure CMake project
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    # Step 7: Build the project
    - name: Build with CMake
      run: cmake --build build

    # Step 8: Run Google Tests
    - name: Run Tests
      run: cd build && echo "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham." > inputText.txt && ./huffman_encoding < ../instructions.txt  && ./Tests/file_comparator_test
    